apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todo-react
  template:
    metadata:
      labels:
        app: todo-react
    spec:
      containers:
      - name: todo-react-container
        image: banil51/todo-react:latest
        ports:
        - containerPort: 3000
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
