apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-react
spec:
  project: default
  source:
    repoURL: https://github.com/acodenil/devops-argocd.git
    path: manifests
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: todo-react
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

