apiVersion: v1
kind: Service
metadata:
  name: todo-react-service
  namespace: todo-react
spec:
  selector:
    app: todo-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

